version: '3.5' 
# uva_notebooks
# Лимитирование памяти с 3 версии только с swarm
# Запуск по команде --> docker-compose --compatibility  up -d (no swarm)
services: 
    datascience-notebook:
        cap_add: 
            - SYS_ADMIN
            - DAC_READ_SEARCH
        build: 
            context: .
            dockerfile: dockerfile #указываем явно файл
        container_name: ds_notebook
        # image: uva/notebooks
        volumes: 
            - /home/at/notebooks:/home/jovyan/work
        ports: 
            - "8888:8888"
        
        stdin_open: true # docker run -i 
        tty: true        # docker run -t
        
        network_mode: bridge